Update trigger-from-repo-a.yml

diff --git a/.github/workflows/trigger-from-repo-a.yml b/.github/workflows/trigger-from-repo-a.yml
--- a/.github/workflows/trigger-from-repo-a.yml
+++ b/.github/workflows/trigger-from-repo-a.yml
@@ -37,4 +37,4 @@ jobs:
         javac add.java
 
     - name: Display Output
-      run: cat A/output.txt
+      run: cat A/output.txt || echo "output.txt not found"
